### ISSUE TITLE
Future Tk version  (8.7) may not match Tcl version (9.0)

### ISSUE THREAD

**Issue by chrstphrchvz** [vadrer/perl-tcl-tk#36]
Hello Vadim, I am curious if you happen to know if there is a reason Tcl::Tk initially tries to load Tk with the same version as `$tcl_version`:

https://github.com/vadrer/perl-tcl-tk/blob/6e4ff85467d11ca83b5460d1ac91fad9f4b437a3/lib/Tcl/Tk.pm#L576-L581

This sort of usage has been present at least since 1.04.

I ask because I predict it will cause a warning for future planned Tcl/Tk releases, where the versions of Tk will not necessarily match the Tcl version. Specifically, there is no Tk 9.0 planned: instead Tk 8.7 will be compatible both with Tcl 8.7 and Tcl 9.0, so it seems there could be a spurious warning for Tcl 9.0 and Tk 8.7.

**Comment by vadrer** [comment]
I always thought that Tk of some version requires exactly the same tcl version;
if this is not the case - then - of course - that code should be adjusted

**Comment by chrstphrchvz** [comment]
I have confirmed the warning (from Tcl::pTk) with Tcl 9.0 and Tk 8.7 (and WIP Tcl.pm support from gisle/tcl.pm#42):
```
can't find package Tk 9.0 at perl-tcl-ptk/blib/lib/Tcl/pTk.pm line 1206.
```

Tcl::Tk requiring Tk with same version as Tcl appeared in this change long ago: https://github.com/gitpan/Tcl-Tk/commit/233a776406b5706be6ec31bc64a61e0f2451bda9#diff-96e9356e1bcff4ae53c4989a768dbba5996b76599be704cf2b691bc5cc6769c1L391-R391. There are plenty of examples in the wild which use/recommend `package require Tk $tcl_version` or `package require Tk [info tclversion]`, so Tcl::Tk may have been following this rather than merely demonstrating how `pkg_require()` accepts a version; but I think this practice is likely outdated and unnecessary (one Tcl maintainer said it is a bug for Tk to attempt to load with an incompatible Tcl version: https://groups.google.com/g/comp.lang.tcl/c/pSTxc1RJPBE/m/yXnlVm7WTxkJ). So I will likely propose just using:

```perl
$i->pkg_require('Tk') or die $@;
```
(Though I may prefer at least `Carp::croak()` or something more helpful than saying just the line number for `eval {}` with no idea what called it, but I can propose that separately.)
